language: swift
osx_image: xcode9.2

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - PROJECT=VirgilSDK.xcodeproj
    - IOS_FRAMEWORK_SCHEME="VirgilSDK iOS"
    - MACOS_FRAMEWORK_SCHEME="VirgilSDK macOS"
    - TVOS_FRAMEWORK_SCHEME="VirgilSDK tvOS"
    - WATCHOS_FRAMEWORK_SCHEME="VirgilSDK watchOS"
    - IOS_SDK=iphonesimulator11.2
    - MACOS_SDK=macosx10.13
    - TVOS_SDK=appletvsimulator11.2
    - WATCHOS_SDK=watchsimulator4.2
    - FRAMEWORK_NAME=VirgilSDK

    # ACCESS_PUBLIC_KEY_ID
    - secure: "DDfAhb73gGH4uE9+6N3IVeoA4TMQvWk4cq08E1dAzxJUZJd3Ka2whItaIY7VNmyqQT8ovujEeOQC7Mzu0wzOugGKPUvM6T2786ds33lluuqsyj4Zdrrz7C6qKPUPHDjWl7QlhrHfpr9Hf+ajQP+nqpCyWdVvuZzEtCSxbu8bvQDeklw6iyxfRECJGe6iz5/Fn+/jEcpO56zHZxq2Iy5HiQWcrJFYKQJmlGziNZ51qDvmrVNq16OLv8upHWstUqpOezKyXUHHPdozulGaMbrcYlRwVWyEp7YbbPUhiAVFLtYyr3rgy2Y/yZy7DdhHpxCHoXcbMdnTxfK68GoTegp9fiKmW5MOdqVqv0FM6uxYh9OwPisXXvb0tPtp4R41v4XXcVD6KFwzKYw4dbZnQgiyjbqhkokjofW+U4XNAP8l3b/6w97yFMbZ8egzczlS8qCS+rqZmNAhcu5eDXNNksc9v9Bz7QYf2QIGQq1fV8c2HCZD0vdrNXmMWuUwbRaOumcd1iG3uryiVFT37HmAVzwtJk6e5xBLyEkFRoGQgbLuw5eVP7GxjiC9jpPLd4daQmJ+DrjHeL6ii5uFVWH8Y+VE1iYgVZCMTJdZcvJQkeYAC+apO7EaNtRD3nR6kJLg90crrJl9pJfbhroS0zX4FENRxrbY6HHkku4tNLaePMGOWtA="
    # ACCESS_PRIVATE_KEY
    - secure: "YS4YwDK9VvZgAjpNsH5KoqmgoNdetA/DfXjDkQn7AO3ac5zeoNLeY7mujWJGQk0feE/6Y3bucAwdObzAJfwMlHUq3cf8c5AX3eobvKo9bCA35db+vgHpsnGIpjIp+TeFjbFxQFNSCR1XkExpDJUdkLEjHCQJRu3dB+dJG+6PNKUYxtLxO/KiEDuUlTgFrScqnMsLs1kb35gqDjKhtTwAq7Z7rBQjhN1U9yL4oct4mPB7tiwQslcSoC3Z8q+pXfrJI0vWXuZtPL5S7SpSWqrxusaU1H3EqY7OLnxE7x9GQybtoPA5b8q5vfuHaeEVBxR/JilABuWqPnjaamnkIM7xGvJcL/yO1AbM5Z7r5QWPXK9PT//ITBNkJzIGWMusMuT4jwf/QcwMUJ1/qH7AtnfuI9v/OXPv1A5/BQoWqT3ZqPhiP6c22xG2UT0lekjjHsjABlyZa3dsnzdTeggZ49gwguqcTYwTMGXu7ZUf4iB3uZ43Yp1nLoRcXhm6Hn5bg9UpIZLDDiVA9f75pS7WzzcDVMl/ZD31wBd7tmwJSlPJDHC9FG04Y1RZ1auWE6tTKfKnTBUJMpy+HQEX8XmD7sgcOVO+B5g535ANLLIe2Z2JsPzPf3M2KlHl/3lPaya+yE7MvPwQfZaiofx5CO0huSNnGK1AxyAOzbgbhAbDiQVxCF0="
    # ACCESS_PUBLIC_KEY
    - secure: "mA17Y57LDQBoRZpay58FaRiBaY3KbGvDlEXtB8MVPoUgxDC7LrN4IdYVc87PKwFJS2DPmyu/2yRp9AJfccG4QnXQlITLTuAGL1UamAw3HuTBDE8fkYEvI1BC4NXG2iB8/UgyzPNjAq0HNnllCT0Cc1/IjMwFV58szJl6ajHE3lGFkJnp10PPb2Pv1mdjQtyTXhB4ZRj3X2sphF4jubTEJ1ZYsrL8f9qotmUscL4NvU3BUQjwvTO+1Og0OXBmYohhx7Gc2cWuTWKJx+72B2M/TeCm2tSII7mnXTlMK+pyLJ8BNDJh050JvkFK1l6PFxugiJ0cBsCWRnxKERMGi/m8tSkwshyESLHFSBTHSkMAxZufXKRuCa4b/QVI/7PhoRj78jQE2wxdfa51Og+qDChsJpyQHE4GhfJLWauxRgHsT4a/AJR6dZIZWgbwBad4UCIILLn140Ly2d6v4VY7TgRNEPi98fxITo7C5GFAH11E5fKHKxnT6/kQs/vrWfhu0uQFWdCXSn7kjjNe02GpDvaj3gWJkrqjfdyIDjo0FSGP2thH5JlbbrJ1F6ZpDzmfbZ5nSRMdi50o5sIllgyen1Fds0SK2C2Q4qZHB0mon78qI5tCEyd0ovQksniZkdPI5T7oiRmRU2bwOA9pWBnSzvQ78bbOIZ0uIjWeUIPakAjpD7A="    
    # APP_ID
    - secure: "df1jSSiV35wJb05I9q2r6vJbaFHJGD1JMV/y+34uXcS53JhA464cJqk3firQF8G+1sVxjarebiO2AhbtYMovemJSnCF9bsLNg1tU0Htb0Y7KjhUrq6V6Rtc1Y35szeV+VwLKBT1v2Cvn6SRfaOrycpyyeT2BbYTnoyZY5MrnIqKEOvQsYNJQ5hyzdpCrsSpb4E6dxgWibxB3Ih22Z/dzjzIhhI2N6TKhqiBz6RWfmPShBfuLtxmDkA/9LfPHxGpd++Pwj0KB4yFQt60YXZaKZD5MvVkFod7tnkunBDhJinwb1M2ZrQaDgnH5pJfYSnhLp4xpz3VwxM+ZCKI5sDFWbodvyKJYfNLigi54v5bb5uXAlwNpI1P1401/mx9dGFfaZsP273mfUnoDU/N1K3dBxeFRGFhZlwTgA5Yg1YoyO9a/vYssG8vNjYBZ0CjAuG2EUGOqLH+Mh2yVLpey28siQkj+uQDy+Qz5yfRiBb5xqljlkUAMAmWS49q2BCbLRCoQQQKv+9rbC28QlH/4bnU9fHLJV4dfjuBMb2NQNH1fSf1En+yURLq91jjmNTEymh+tWDkAe6eifBFs9z1L9CLkvVxrUFoVcesM6VNy5VTQzLpocwCOOotMeDWISHddfGkW799dnZnybVVX2EX9GmtbU/7h2KEh9jM4t7ypVpYURdQ="
    # SERVICE_URL
    - secure: "iBAw4GTBsL/q4KIfHfS36r9XRB62mfXm9a5iqxmXNmmykfTuJphAboumSVK0yFqDbO9Ehcd94JBMPXfKknCkwtjvtAAKlI1EcGi4FApKg0Sp1Gc0xHNrwl4t8mwS0ziYWBKobRl25gzbmLlyN3Al6GNcVRn/3NrYcKA75MS0hV/wY4g8Lcwcp8fO03+Sk2hKHHONrkO4FhAj9GAC6eCmlD7JuvaeNKj87FulQicMEHq8qHV+0p1SpfWc66cJcYKuQ6L8bwcv3NEwAlEcJUo2cRi9SbfXF5jjYOj1VvLecuT7OmesD7xi4DKaGD9Vxah08p73NfgJVsRz50qXKCFPt2JEsGnJ3h7gMsTgDOQyww8DMhZdPQ8q7gJi3jv8JVEqhEMX6hFS1ysDvOfPmpC+j27jvAOqygvyBs11i+JKU81ayEi7wS6SoMlf1j3AT7d88nUq0Kf3TpJwn12qrvmgaBslohv0pBai7Qs2jKRiG7a0pTzIXVbjQVaC611LDNwlsaeETjclz/aiEcrq9kCIcf9Q4e7/HwlvSuWQLIWI6eov2pMiTLmtZ3PphvKD+Uv1gW6zGNOt7v6EG6bKW22B1hRVfIcDEm39Inu4SXaqbIYTYOlCnhvyT9g3/d/LDAilIQqxxzc0hqY00l/cuJ9LmroydSuTTN9XTiJFxnFSzq4="
    
  matrix:
    - DESTINATION="OS=11.2,name=iPhone SE"            SCHEME="$IOS_FRAMEWORK_SCHEME"        SDK="$IOS_SDK"        TWO_STEP_BUILD_ENABLED="YES"    CARTHAGE_PLATFORM_NAME="iOS"        RUN_TESTS="YES"    PUBLISH_DOCS="NO"     PUBLISH_CARTHAGE="NO"     POD_LIB_LINT="NO"
    - DESTINATION="arch=x86_64"                       SCHEME="$MACOS_FRAMEWORK_SCHEME"      SDK="$MACOS_SDK"      TWO_STEP_BUILD_ENABLED="YES"    CARTHAGE_PLATFORM_NAME="Mac"        RUN_TESTS="YES"    PUBLISH_DOCS="YES"    PUBLISH_CARTHAGE="YES"    POD_LIB_LINT="NO"
    - DESTINATION="OS=11.2,name=Apple TV 4K"          SCHEME="$TVOS_FRAMEWORK_SCHEME"       SDK="$TVOS_SDK"       TWO_STEP_BUILD_ENABLED="YES"    CARTHAGE_PLATFORM_NAME="tvOS"       RUN_TESTS="YES"    PUBLISH_DOCS="NO"     PUBLISH_CARTHAGE="NO"     POD_LIB_LINT="NO"
    - DESTINATION="OS=4.2,name=Apple Watch - 42mm"    SCHEME="$WATCHOS_FRAMEWORK_SCHEME"    SDK="$WATCHOS_SDK"    TWO_STEP_BUILD_ENABLED="NO"     CARTHAGE_PLATFORM_NAME="watchOS"    RUN_TESTS="NO"     PUBLISH_DOCS="NO"     PUBLISH_CARTHAGE="NO"     POD_LIB_LINT="NO"

before_install:
  - set -e
  - set -o pipefail
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - xcodebuild -version
  - xcodebuild -showsdks

script:
  - carthage update --no-build
  
  - |
    if [ $TWO_STEP_BUILD_ENABLED == "YES" ]; then
      # Build Framework
      xcodebuild -verbose -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug clean build-for-testing | xcpretty;
      # Build Framework in Release and Run Tests if specified
      if [ $RUN_TESTS == "YES" ]; then
        xcodebuild -verbose -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug test-without-building | xcpretty;
      fi
    else
      # Build Framework
      xcodebuild -verbose -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release clean build | xcpretty;  
    fi

  # Build with carthage
  - if [ $PUBLISH_CARTHAGE == "YES" ]; then
      carthage build --no-skip-current;
    fi
  
  # Check pod lib
  - if [ $POD_LIB_LINT == "YES" ]; then
      pod repo update;
      pod lib lint;
    fi

after_success:
  # Generate and publish docs
  - if [ -n "${TRAVIS_TAG}" ] && [ $PUBLISH_DOCS == "YES" ]; then
      ./CI/publish-docs.sh;
    fi

before_deploy:
  # Generate carthage framework
  - if [ $PUBLISH_CARTHAGE == "YES" ]; then
      carthage archive $FRAMEWORK_NAME;
    fi

deploy:
  # Upload framework to gh-releases for carthage
  - provider: releases
    api_key:
      secure: KoovDyi1gvzeDdGWKUPq2IEkpiC/6PadkIVEEkh+lyqBpWliC3KOu3cD/RXBAJw84g+YNUFr80776Xv/QPdj1LzTaN0Ri2HpfdyEPFOHvhQKzxJG/jm4BZBV+CNJfLJZndvrF/ImeZgkRTk/MR83urBJfl4/UnPj77CZg+lpG88HtV3oN8OqxBPEy34D4MTsg3twL/Z/XYlYl3BMzVzJzY9teHxwwcEgYwsk8i0GUggTRO/cyTDqg9X/g1rqEPWzlX4S/hGVBCB6qrRrXXK96DYUic39LdNbt+so+8hJHO0ETxTtt7v1B59qZ0OUlQfSBeUqBIrJCFm3U7hR4UJqHbsUl3dyQ/WrZv28/AaAFYCRDTqZSE7oTXR9IhY+jlhLrU3n7ukYoG1Yhr11MQN1z8DgzIhdyWWX2DK16kgsIFC99AxkRQzmJdQqXMmtrR79UN0/8eKE4WAm8Ihji6fTTCm4zx3sfi1bTJ8bdzbFhgpqqUpAuKc7yGbOhRsnYsL+TTpQiVCGju/nUNEHmwUy+MmYkHlR8l1OHz0mGbZQMecUXZ8h4Be7RONIOaDB05Gi4wkcaywDkoUdEb9LuFIme+Ws+PbNEKwkcPIiv9tGzh/ROk9t7qWj3FU3R1oLQImpwBbIlywyelWrNfWE5QG928UmYNyK1RrpRBL8ekqqXlw=
    file: $FRAMEWORK_NAME.framework.zip
    skip_cleanup: true
    on:
      repo: VirgilSecurity/virgil-sdk-x
      tags: true
      condition: $PUBLISH_CARTHAGE = "YES"

  # Upload docs to gh-pages
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: "${TRAVIS_BUILD_DIR}/docs"
    on:
      tags: true
      condition: $PUBLISH_DOCS = "YES"
