language: swift
osx_image: xcode9.2

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - PROJECT=VirgilSDK.xcodeproj
    - IOS_FRAMEWORK_SCHEME="VirgilSDK iOS"
    - MACOS_FRAMEWORK_SCHEME="VirgilSDK macOS"
    - TVOS_FRAMEWORK_SCHEME="VirgilSDK tvOS"
    - WATCHOS_FRAMEWORK_SCHEME="VirgilSDK watchOS"
    - IOS_SDK=iphonesimulator11.2
    - MACOS_SDK=macosx10.13
    - TVOS_SDK=appletvsimulator11.2
    - WATCHOS_SDK=watchsimulator4.2
    - FRAMEWORK_NAME=VirgilSDK

    # APPLICATION_ID
    - secure: "Zeo7F9hGJ2rmFzMGB9x6WNUqO3+2du066swAQADBeoaO59+xkOrT5pv3KacIY2BS4GuEDbY1v3Fi73y2Fk+0smKrGn1lvigs4ZdVDw/1qxG2SxCG3XC5XMXq/1SSbWHpEi+Tn/TVkNav9Xmm7JbB5I0+7TH2Nx/Bf72UFP3rogIijyjvEWJcYn1DmGfYpbLKm4NIBXUZtIvFCOhdR8cmGdoZcQnVroOMMhrzP0kArNX8UwExe1TgbliQFpvl9ZmSuYPcZTAXobGz9GLTW0O17F7KWYcYguq2mjMpb74fuUnuP4ngH3YV8WNMAINUAyhFDVNMD7Ce7gxH2Mwb6anD+t59d1Jjhcg60V756knKmDOngaoi4L4SNdslpHpSESNZqXv8/ieOoScjOh7xJZ/txSGHq4ecOU5fMmjO7n/NPTTcuMqINgxL6za6UvcGK5KmOScLOcl8F85i2CFgn/JaSET+Wi6wwyL/qcHsELAoj09XbYP9RnVhghJsnNMt3yGdtojd5Ls46o4I+NErY+/9frYnivZ4usDSsNhBnZ7oo92FMR8b73MDxxEKEKUsiIkyvApxh0KueO+UzujSpEJKtr45CCz0oezBBqwt1g9zaDGOAFtV/DLowQ5nph11KHSmsgjZXUYuyXmJZCHf7yEqsjhoySPsou6fLV60a2TDLdc="
    # APPLICATION_PRIVATE_KEY_BASE64
    - secure: "HIfUv/cDDex3HgoEbSqS9w3r+0Eq4yzX8S94WzN7Q56EVYOO9Tt8Vgfwl2YUs6YLbkx8qe+FVtKKlTiJ1aGX2/0ww3N1Ae6aL1iepKdQQ4BQl/mXMQ3npkAsSOls6shMX1+Hk7ke32TdHzWaeLBwE62MUlpdNyctbV6cISE3hVByCAOmJwhvh+8bh4rv79+aphGJcgaVtxXyfvAXiRSMWO1M9VnLFWSsmmsjreEvlNho5QJtbBbMytaKp+j7gkexuVo/d7DpWUVGoG26367nstQwkf7WOips/Cucz3Jifii6EXoTWUnecQdHmSgUq4bgTlgq6ifwrGj3mJzjt2pdIYiF9HZie/cGZP8BfgshYEpXq1/uQnl1wTiUYtcIfdO/8NRReoGKsugBdd2cndnH4qfQq5vitEHYY8VnERmBFIHfquHanxqYB/xvkuFPgrzcjsM0B7MSw7o5bedr0/0a9vsGgMLd8COHR3kQmWnjG/OMEhtg7kNkppfLm4UQfmC07FO0e1PmYaKRPQn2wXxYFf41eHBgsPt+l2VAKXYOkUqaaofuylMiAi64QEE5028LssBPiC1W5iKwKLJVHw43iE7Y7ruxjMyr/wevoTP/cCOjePAGWtdy7dEzSH0p2dOHoaAv3QjDJMWeDqEbMoUFRhaXbPM+k8jPgPx7RyO33Hw="
    # APPLICATION_PRIVATE_KEY_PASSWORD
    - secure: "f5YkuM74LWhztjDavcHl9NMZ0Z29nf9yYNWxKTMH/KJEDva08RXyovtMXT+RkI79iK7TP/d1Yhv3YP1QqA3U2xsMq4b+Iq9p4XzxwgW4/uSBk+Gmw3VcW0ij1qZnaXFMdLLZkgLw/liW6EbRmjg7+bwOoZoVnt0/ZIDYJV5HSbhIBMgpDVWMKmy2u3va7kqWMJcAlsDerwZiVjbbkuu/KgGDpHmvwUMBgmF5G2A+Z655mZmZW8c4as3pKLOjq0C0s38KCLWjosYJppOtaCwErIdTdVd3CcYqUNjLamqDsklq9YffFO5tL3UVbxn6qSccP3S5ccLl9m4YpX1BAZ9Xb2yWGjlQSZPBu/4UiBoL4tSQA2tmisptKp3v0C7pCweO0ltOOwR2VY7kPZyeDvaQPLqnUqH+1IXrWmA9D02PmqLcGDI29eXU11NaXcadmAx4XhxNgHiBUSOh78UWywNUkF0wn+ly7zEEEi6Itm7J7M+66rjE2ch5c60J8avHOba9b4ZjD9THPtFO4e7KTo+gY9eNcLa78XdFKmCqFEZSFTnL6HAEvB8UlTHXIrHOO/d9DULWMjyBnv8cAFxMOmmqKjwXVHqYdjO2kfKup9VGvSH8bezzZ87mmevi9Nzqp/tOAiTz9132lWbgYDk7pb7sMz/9TDiN4ynfG5E8rRX+2QA="
    # APPLICATION_TOKEN
    - secure: "OeOh1DzeebPF1dzHjy75rNNVhHOpA/0R1eRhPmNuX1eKSnPEatmi2iSDjf9Niak0o/GwQjOZWoQtWpDnNtQs+nez469D1UD4ScXyDg9cpOEcAtHTEpSP+10mE/ezUatW4k8Wzt0BYFkwLc8IL/wx/IuCO4J7TtytCowc1ujqgxgPxJiy0sRgBrkrXVS18OgMcjEAIlLXGJqPNk2rKWeg0376MrE7UYhtMbPUUZcvh2st6Sw8S2tzkbcxmNNaZW7yAR1JRUrCMGoZQzebWEQoKOuiAQBDLCbUE9OXf8DHuWqvHGAROeQZ0BE/ZusYBpogYZBJO2auA/wbygXvgvkhZ3NiHCmyenEkWjRG/3z0xdH0oQ6PSmWdoAuJB3ADcUqZYc/hHguC7sahvGEHnjjmskwVJMiplnA+JI9RdK8kXojVmKJkhneGMXGbYX5wBRZZi4qrl8Gjb02sYBwjjekTf8ZoOPMgfKxh+YFP6owvZXgaRaH4TiEsesaMMkwBuIeXtfykQU/IDM4Bf+Zz2T9U4QWmwBGQQXeRIDCnOxFAHci8opH5yk9Ci4JezDcmzGV03rB3xNEap4ZsxK0P/HSqXUvFR427X/GbCIgq6ccwxJOUAIxQjDAaUhfA5zwU3JulYLJY6hSxSwiy+ccDbjEnQxMT7jM9pqQ8T6ersJ7hpjI="
    # CARDS_SERVICE_URL
    - secure: "ppZfOLSxYuOFOOf58DfgH0uzYTXh515JBnG3+t56oaiOVmsU1MbH1zxT30k/1yurfrpTTgfUxPu/OD/UMTOfhWgywzTtw7pHB1HWnlUlMA5kWuE73rHWeRs1Lm5SNKgcqYecU1EzGisoGDGpiMHYBPRPDKu+7I6srBWp6rpu5n/DdMIYhUCbddDOmJm/m7DJUWyHSOJNYrLvn75nKOunUD+Mz1aTr7mO7i8oHqWTqXWfDoHirMBgejUrnO4SILwNzkS3FNE7EdjEnci72VA+RHoqtw6u6qGE++QwCj7FZA2WQFae/rY91fB4P+kC6MizJVMTrBfzMtyUEdRUJYv0Fil9rMMFEkpzUfMmTciAzkw4zQd7EdggTL84EM45PUu/pX0CNGgz1+i47VJIrzlxPQzLJrL/pg/8+9S26uYtt321QlP0FbQYuPwnSD8vq//UykGuIkRIUrQ1JeXvST0FrxJTIj8IpM6BE9qjRAdJgyCaCGsqBp8yBd1bvwf3kbAuaQWT1xBWWOThmwTElvQdkdAY+Nt0dGmlGHq+OfI+RuEXk0lWZmV0/O/bl3GSH+0PpJTXiGmyVgejiLncWhui0/88o3NpMWFxg67B/f8q1wu5CpMbvlDTThSqfOyqoeklNwK+Nst6Z7WYFigmYM/FpXF9kvjAsh03EK1OaGTu7q0="
    
  matrix:
    - DESTINATION="OS=11.2,name=iPhone SE"            SCHEME="$IOS_FRAMEWORK_SCHEME"        SDK="$IOS_SDK"        TWO_STEP_BUILD_ENABLED="YES"    CARTHAGE_PLATFORM_NAME="iOS"        RUN_TESTS="YES"    PUBLISH_DOCS="NO"     PUBLISH_CARTHAGE="NO"     POD_LIB_LINT="NO"
    - DESTINATION="arch=x86_64"                       SCHEME="$MACOS_FRAMEWORK_SCHEME"      SDK="$MACOS_SDK"      TWO_STEP_BUILD_ENABLED="YES"    CARTHAGE_PLATFORM_NAME="Mac"        RUN_TESTS="YES"    PUBLISH_DOCS="YES"    PUBLISH_CARTHAGE="YES"    POD_LIB_LINT="NO"
    - DESTINATION="OS=11.2,name=Apple TV 4K"          SCHEME="$TVOS_FRAMEWORK_SCHEME"       SDK="$TVOS_SDK"       TWO_STEP_BUILD_ENABLED="YES"    CARTHAGE_PLATFORM_NAME="tvOS"       RUN_TESTS="YES"    PUBLISH_DOCS="NO"     PUBLISH_CARTHAGE="NO"     POD_LIB_LINT="NO"
    - DESTINATION="OS=4.2,name=Apple Watch - 42mm"    SCHEME="$WATCHOS_FRAMEWORK_SCHEME"    SDK="$WATCHOS_SDK"    TWO_STEP_BUILD_ENABLED="NO"     CARTHAGE_PLATFORM_NAME="watchOS"    RUN_TESTS="NO"     PUBLISH_DOCS="NO"     PUBLISH_CARTHAGE="NO"     POD_LIB_LINT="NO"

before_install:
  - set -e
  - set -o pipefail
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - xcodebuild -version
  - xcodebuild -showsdks

script:
  - carthage update --no-build
  
  - |
    if [ $TWO_STEP_BUILD_ENABLED == "YES" ]; then
      # Build Framework
      xcodebuild -verbose -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug clean build-for-testing | xcpretty;
      # Build Framework in Release and Run Tests if specified
      if [ $RUN_TESTS == "YES" ]; then
        xcodebuild -verbose -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug test-without-building | xcpretty;
      fi
    else
      # Build Framework
      xcodebuild -verbose -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release clean build | xcpretty;  
    fi

  # Build with carthage
  - if [ $PUBLISH_CARTHAGE == "YES" ]; then
      carthage build --no-skip-current;
    fi
  
  # Check pod lib
  - if [ $POD_LIB_LINT == "YES" ]; then
      pod repo update;
      pod lib lint;
    fi

after_success:
  # Generate and publish docs
  - if [ -n "${TRAVIS_TAG}" ] && [ $PUBLISH_DOCS == "YES" ]; then
      ./CI/publish-docs.sh;
    fi

before_deploy:
  # Generate carthage framework
  - if [ $PUBLISH_CARTHAGE == "YES" ]; then
      carthage archive $FRAMEWORK_NAME;
    fi

deploy:
  # Upload framework to gh-releases for carthage
  - provider: releases
    api_key:
      secure: KoovDyi1gvzeDdGWKUPq2IEkpiC/6PadkIVEEkh+lyqBpWliC3KOu3cD/RXBAJw84g+YNUFr80776Xv/QPdj1LzTaN0Ri2HpfdyEPFOHvhQKzxJG/jm4BZBV+CNJfLJZndvrF/ImeZgkRTk/MR83urBJfl4/UnPj77CZg+lpG88HtV3oN8OqxBPEy34D4MTsg3twL/Z/XYlYl3BMzVzJzY9teHxwwcEgYwsk8i0GUggTRO/cyTDqg9X/g1rqEPWzlX4S/hGVBCB6qrRrXXK96DYUic39LdNbt+so+8hJHO0ETxTtt7v1B59qZ0OUlQfSBeUqBIrJCFm3U7hR4UJqHbsUl3dyQ/WrZv28/AaAFYCRDTqZSE7oTXR9IhY+jlhLrU3n7ukYoG1Yhr11MQN1z8DgzIhdyWWX2DK16kgsIFC99AxkRQzmJdQqXMmtrR79UN0/8eKE4WAm8Ihji6fTTCm4zx3sfi1bTJ8bdzbFhgpqqUpAuKc7yGbOhRsnYsL+TTpQiVCGju/nUNEHmwUy+MmYkHlR8l1OHz0mGbZQMecUXZ8h4Be7RONIOaDB05Gi4wkcaywDkoUdEb9LuFIme+Ws+PbNEKwkcPIiv9tGzh/ROk9t7qWj3FU3R1oLQImpwBbIlywyelWrNfWE5QG928UmYNyK1RrpRBL8ekqqXlw=
    file: $FRAMEWORK_NAME.framework.zip
    skip_cleanup: true
    on:
      repo: VirgilSecurity/virgil-sdk-x
      tags: true
      condition: $PUBLISH_CARTHAGE = "YES"

  # Upload docs to gh-pages
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: "${TRAVIS_BUILD_DIR}/docs"
    on:
      tags: true
      condition: $PUBLISH_DOCS = "YES"
