language: objective-c

osx_image: xcode9

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - PROJECT=VirgilSDK.xcodeproj
    - IOS_FRAMEWORK_SCHEME="VirgilSDK iOS"
    - IOS_TEST_SCHEME="TestApp iOS"
    - MACOS_FRAMEWORK_SCHEME="VirgilSDK macOS"
    - MACOS_TEST_SCHEME="VirgilSDK macOS"
    - IOS_SDK=iphonesimulator11.0
    - MACOS_SDK=macosx10.12
    - FRAMEWORK_NAME=VirgilSDK
  matrix:
    - DESTINATION="OS=11.0,name=iPhone SE"  SCHEME="$IOS_FRAMEWORK_SCHEME"    TEST_SCHEME="$IOS_TEST_SCHEME"    SDK="$IOS_SDK"    PLATFORM_NAME="iOS"  RUN_TESTS="YES"  PUBLISH_COVERAGE="YES"  PUBLISH_DOCS="NO"   PUBLISH_CARTHAGE="YES"  POD_LIB_LINT="NO"
    - DESTINATION="arch=x86_64"             SCHEME="$MACOS_FRAMEWORK_SCHEME"  TEST_SCHEME="$MACOS_TEST_SCHEME"  SDK="$MACOS_SDK"  PLATFORM_NAME="Mac"  RUN_TESTS="YES"  PUBLISH_COVERAGE="NO"   PUBLISH_DOCS="YES"  PUBLISH_CARTHAGE="NO"   POD_LIB_LINT="NO"

before_install:
  - set -o pipefail
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - xcodebuild -version
  - xcodebuild -showsdks

script:
  - carthage update --platform "$PLATFORM_NAME";

  - xcodebuild -verbose -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release clean build | xcpretty;
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -verbose -project "$PROJECT" -scheme "$TEST_SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release clean build test | xcpretty;
    fi

  # Build with carthage
  - if [ $PUBLISH_CARTHAGE == "YES" ]; then
      carthage build --no-skip-current;
    fi
  
  # Check pod lib
  - if [ $POD_LIB_LINT == "YES" ]; then
      pod repo update;
      pod lib lint;
    fi

after_success:
  # Generate and publish docs
  - if [ -n "${TRAVIS_TAG}" ] && [ $PUBLISH_DOCS == "YES" ]; then
      ./CI/publish-docs.sh;
    fi

before_deploy:
  # Generate carthage framework
  - if [ $PUBLISH_CARTHAGE == "YES" ]; then
      carthage archive $FRAMEWORK_NAME;
    fi

deploy:
  # Upload framework to gh-releases for carthage
  - provider: releases
    api_key:
      secure: KoovDyi1gvzeDdGWKUPq2IEkpiC/6PadkIVEEkh+lyqBpWliC3KOu3cD/RXBAJw84g+YNUFr80776Xv/QPdj1LzTaN0Ri2HpfdyEPFOHvhQKzxJG/jm4BZBV+CNJfLJZndvrF/ImeZgkRTk/MR83urBJfl4/UnPj77CZg+lpG88HtV3oN8OqxBPEy34D4MTsg3twL/Z/XYlYl3BMzVzJzY9teHxwwcEgYwsk8i0GUggTRO/cyTDqg9X/g1rqEPWzlX4S/hGVBCB6qrRrXXK96DYUic39LdNbt+so+8hJHO0ETxTtt7v1B59qZ0OUlQfSBeUqBIrJCFm3U7hR4UJqHbsUl3dyQ/WrZv28/AaAFYCRDTqZSE7oTXR9IhY+jlhLrU3n7ukYoG1Yhr11MQN1z8DgzIhdyWWX2DK16kgsIFC99AxkRQzmJdQqXMmtrR79UN0/8eKE4WAm8Ihji6fTTCm4zx3sfi1bTJ8bdzbFhgpqqUpAuKc7yGbOhRsnYsL+TTpQiVCGju/nUNEHmwUy+MmYkHlR8l1OHz0mGbZQMecUXZ8h4Be7RONIOaDB05Gi4wkcaywDkoUdEb9LuFIme+Ws+PbNEKwkcPIiv9tGzh/ROk9t7qWj3FU3R1oLQImpwBbIlywyelWrNfWE5QG928UmYNyK1RrpRBL8ekqqXlw=
    file: $FRAMEWORK_NAME.framework.zip
    skip_cleanup: true
    on:
      repo: VirgilSecurity/virgil-sdk-x
      tags: true
      condition: $PUBLISH_CARTHAGE = "YES"

  # Upload docs to gh-pages
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: "${TRAVIS_BUILD_DIR}/docs"
    on:
      tags: true
      condition: $PUBLISH_DOCS = "YES"
