language: swift
osx_image: xcode9.2

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - PROJECT=VirgilSDK.xcodeproj
    - IOS_FRAMEWORK_SCHEME="VirgilSDK iOS"
    - MACOS_FRAMEWORK_SCHEME="VirgilSDK macOS"
    - TVOS_FRAMEWORK_SCHEME="VirgilSDK tvOS"
    - WATCHOS_FRAMEWORK_SCHEME="VirgilSDK watchOS"
    - IOS_TEST_SCHEME="TestApp iOS"
    - TVOS_TEST_SCHEME="TestApp tvOS"
    - IOS_SDK=iphonesimulator11.2
    - MACOS_SDK=macosx10.13
    - TVOS_SDK=appletvsimulator11.2
    - WATCHOS_SDK=watchsimulator4.2
    - FRAMEWORK_NAME=VirgilSDK

    # API_PUBLIC_KEY_ID
    - secure: "kKXkzJgcERq2GsOJVGNjE0+AAAzxiORhsrCw18mDzpxnzuYLYSZzWo1GKiSWONTZpzPwjICl8EBT7PpCdUofZodBEv7bKxi6JnqLyjfFfgSjyziy5Qd/8JFCxwnAGmwMR2TXEdvqj58Iq48hxF1vXsyjOtNG+v6iDMTGWXRqCU47cTDLcZct/zMdmeSBfeKFvfBrNT8mmGbJ5lSYeYXUcjmIhO5Fg/hXnBWFo5mRI0h5xaGNIEGF+gImTa0AIj0jtfu857m0fdGmvJrzpeHVGG1w9vfVpnNNbgGpeDlgkO93aWEzT2JhnlYXOUXcsJqdIlJHzW53bGNKcKG/XFDL8tbdEg5yUEW4sb02beIUBbbgnOEXzEaC1FUP8MS2T7LXTwqnupJ1Myys13X6pD1xlAmjF+RZCmARaU35j1qt/iHcP1NSI9vLYPWY7RMVuECpbmQcmSUZE07aWA/39CMCkiXRrMkoLhJV0d56+m500xKdGvvF5tyre0lTUtsM/E+Cy5zYhgNKBltk4jhfNDw9+P2DWdci7IW1aRqwLYTQ6HVbLxMjY/ukDnKo6zgz6nWqeyv7d1uocowitQ8HiPnD5ZVcUsUaYY2OsG9FkCU2bNA1CiMd8lCbhsjsKIlePmVK9pgyNvKiLB8vC5p5uChi+DehTdRZtQtQqW+xXAQXICk="
    # API_PRIVATE_KEY
    - secure: "IkPh4W5UiSRBy+HlCopRLwPU5RAH22LDwsYYLlVQJdVC0ARWgsBb2pg0x9Qhs+fK5ZVeE3JcJ35tzTR8r4pC/sxT9BJxb+PjMwJsT/AeGdg7jqfYa1d1OUamjaLyJM3T6MZ3788FlIDGgFNBG1ITQPuEXGbN0uxoYlUa6UNbEl2Q5NoSpOkEwIcmXWqNNdHcRF7vsffhHjjSQABk7J0H+rUYp1qMc0oL2lmVPiPRI6ivB9TVoapM8quhz0V5uvQP6ioHr2BkwW15eUeX+ob3zz4C2V9Ec2TPYQ8WkmKT5Fe4kKS2rTy2OpJUWZECgW2/5PYsQ8dIXBJyT72Fh19M+yy9Fb0WlVF3S0I+IclkfN3BSonNZa7X8zopcBUCTqmqlRborPse/Gxlrf/gBETeKWJak6QDmgB0wCMQTC9+cxnNcst7zLyR21Lq/BIc9FfKyGnJQKtTi7YaIG1WOeqN4T3/40+HQ8yXl547e88FH/mUkxqCzjMp/DIA7wNeGGjBiu8o1nRWsz83wXo5illmPvVlaJhpG0vsvP88O9JAj5P/jinMtNfFRLKRF9VkmZ6NVBKx46vS4UkKdzO7kT/JaBxcl0QEg6SmAs/JMFtruEn5B3HjyaBloCkMqD/iL21c6WytuYicMIoI9p/OGlj+KWpV7r2O6q0OoysMbzX3bTY="
    # API_PUBLIC_KEY
    - secure: "sBKPHtGh5VyURZ8z8Dm6/jo66yOAdUDWuHay49Teb9bHKYuy4MtQmk03wcp11sINtN1TKrjlykgxg334RqO6YNVbrMEeXNFtJMN4hHh87D6BTNE8kpAWJfIr2100zHJGoJRKCeSmGWMN/jL0PVofnHXvn1LLL7p7OK5/InlxJXghWM2glRH2rGZ0Rxt1J2eLzn/y2RigKrifaAPglml2HDHI3rjdz8+Yll4coCY3jqbDdbqmRy5nALicLhCfuALLbBtJHvtmdwcbM0hVJLnr0NnS7wdnRmSrsSrWFAGk0Xfz4CKElVUq1VTwu0qVdZgSBvm1AD0sZXr88YmUlENmKC81ixIjQpGkP8uIBa5ZR3/lqyLPRkA7nY/kBbX1nwwVY+qiLtSr8GjWdsaSoySpBXWTjt2aPT8ibaMlHtdbWft26LsXVABi0i4oH5ne5tc12rkuNiPlAkKnBhAm+8sCKxrlNthI5oioq+L85JNcvFB2SSQbDg58P87ufkJwZEnAajA1Z4XSFiGXDtYjswD5lcC7L+qqeOOpxys3+HLtj//fjCZd0yCZc1iiubhAfOJOxxMhneOqdMZ+RUpVZ7pdUJIO6J5r4z0x8jxPyvq8Bwih7JB/lg2py5BLKtJWp3v2nXTbTqewS9z81dga2d2fYhnc6VVUTwMbPS9e0VS80NY="    
    # APP_ID
    - secure: "mjyRKTE3I3gi5ijL0AXL7gVZXv59knpeq2O2kkz3ea4ji1sTKratTYeW3Pyjyjh6xgqIlYDddxg+Z9hP9uudLnzwCSSi8/sHoOUwpJXObVSZoaw8c+13DT6n8X1qIu+kkJYVIsihDZnBpDdViQsG5s7ed2veLIpZYY63FBDR/mPDuOhtkygcSiJVOKsoh4wgY3EJg02cE9x/bLESzbH+o91kGXjTeTwO1Ru3wWzQoY70o82Ib5KHhMQ1jQgabcToVJ/Eq44lSrldGVPz98lhm6LrM04+yL6t4gX7FwG0n1gMqEJBnrdMQbbj9fxbe3BhyG4K+x4WrStJEKiDlcXsMhFrnNCwPj66Xr6m55SPPLyElKoGRVL9cZ9s4sWoFxb8yXJ6xmi++ZDgfienmcdSSvooq/lRg1KbKjeokdDvi2t83TKqYYbG13Daw2JDFGyYC80RfNsB7EoJzl4aI+UjTLI9/MRVo71rCuW9TajA60zKpzmlj4y9JIs9dxgDWF1Lmw1Q2z5HoRDfGeg5jwA6dJzEdPfZB/Xid/A3NwZzDhe7jVEujp0BEQzFQKJbamGjRJZSON6wsSrFe89t4aZ1w9quGbvmocr2gTxnvJFl+t6F0IrUaWULy9+xbf1ZDCytkkdSTMQb1si5OgnYoCOtdpQLESKuc3G4rXuoWgsb1Ys="
    # SERVICE_URL
    - secure: "a0/NZqVtRzdjLL96h2tQyRmbf8+QhAu8G7gsSsHzuoIDieZcQ7aEWt17c49iLo2W/xJ02CEGHlKzykdT0P7b9eykxyGEp9ToiNMC7QNkyIq10gTN8ybtX9+4rWygC3f3BbWlD0cpQldX6QigsbqI2LE1bTR46Czsxq1Ntq5S3gMaMHZlf/nobzeptDfr0gUGzaB2uzyEivo1YCPo4MRswuYwfwSwKgWwCEFSvNSekVIKtK7IMV/rjTPIpPwi6ypN7iv3xOrW0c6fR9XlkxH+z2q5k7x1AKLbpxpcLEjsKpajN0Y1pR/ZP/Suq8rCzhyw6u9HINiU+SKSIV/uFxUaxm6dK/a5sfABIj3Kdbz1fBMs7oSUqo/rsFu34KcWFK9RdiunBuYFBg2vjTkeW/m9K6kKv8pEZ1eqfhSs9bY/8CZEARL3RTnmSvTHn5vjj/R4ONNHYZhodb8LOz8md30JvhYxERLW+aDXNxG/6TFw/sIZcPZUJWFiC/OTuuLQeSdrxetPhVP1y5C4dCfBz993rDiHPgs4WOofYrS5M+Cpn+OH2Jr4tdOibQQd8C3P3qZFJ2k9IeCVKfftzjSnDHhjUHl7bhn+PBImrILCcaT2+ty729pLiG7BLtNlwV5tsZaE1gbH0o69GdWoOo6jrmkycanMpXOSX9Z70/hn3WrVOHk="
    
  matrix:
    - DESTINATION="OS=11.2,name=iPhone SE"            SCHEME="$IOS_FRAMEWORK_SCHEME"        SDK="$IOS_SDK"        TWO_STEP_BUILD_ENABLED="YES"    CARTHAGE_PLATFORM_NAME="iOS"        RUN_TESTS="YES"    ADDITIONAL_TESTS_SCHEME="$IOS_TEST_SCHEME"     PUBLISH_DOCS="NO"     PUBLISH_CARTHAGE="NO"     POD_LIB_LINT="YES"   SWIFT_LINT="NO"
    - DESTINATION="arch=x86_64"                       SCHEME="$MACOS_FRAMEWORK_SCHEME"      SDK="$MACOS_SDK"      TWO_STEP_BUILD_ENABLED="YES"    CARTHAGE_PLATFORM_NAME="Mac"        RUN_TESTS="YES"    ADDITIONAL_TESTS_SCHEME=""                     PUBLISH_DOCS="NO"     PUBLISH_CARTHAGE="YES"    POD_LIB_LINT="NO"    SWIFT_LINT="NO"
    - DESTINATION="OS=11.2,name=Apple TV 4K"          SCHEME="$TVOS_FRAMEWORK_SCHEME"       SDK="$TVOS_SDK"       TWO_STEP_BUILD_ENABLED="YES"    CARTHAGE_PLATFORM_NAME="tvOS"       RUN_TESTS="YES"    ADDITIONAL_TESTS_SCHEME="$TVOS_TEST_SCHEME"    PUBLISH_DOCS="NO"     PUBLISH_CARTHAGE="NO"     POD_LIB_LINT="NO"    SWIFT_LINT="YES"
    - DESTINATION="OS=4.2,name=Apple Watch - 42mm"    SCHEME="$WATCHOS_FRAMEWORK_SCHEME"    SDK="$WATCHOS_SDK"    TWO_STEP_BUILD_ENABLED="NO"     CARTHAGE_PLATFORM_NAME="watchOS"    RUN_TESTS="NO"     ADDITIONAL_TESTS_SCHEME=""                     PUBLISH_DOCS="NO"     PUBLISH_CARTHAGE="NO"     POD_LIB_LINT="NO"    SWIFT_LINT="NO"

before_install:
  - set -e
  - set -o pipefail
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - xcodebuild -version
  - xcodebuild -showsdks

script:
  - carthage update --no-build

  - |
    if [ $SWIFT_LINT == "YES" ]; then
      brew outdated swiftlint || brew upgrade swiftlint
      swiftlint
    fi
  
  - |
    if [ $TWO_STEP_BUILD_ENABLED == "YES" ]; then
      # Build Framework
      xcodebuild -verbose -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug clean build-for-testing | xcpretty;
      # Build Framework in Release and Run Tests if specified
      if [ $RUN_TESTS == "YES" ]; then
        xcodebuild -verbose -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug test-without-building | xcpretty;

        if [ -n "$ADDITIONAL_TESTS_SCHEME" ]; then
          xcodebuild -verbose -project "$PROJECT" -scheme "$ADDITIONAL_TESTS_SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug clean test | xcpretty;
        fi
      fi
    else
      # Build Framework
      xcodebuild -verbose -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release clean build | xcpretty;  
    fi

  # Build with carthage
  - if [ $PUBLISH_CARTHAGE == "YES" ]; then
      carthage build --no-skip-current;
    fi
  
  # Check pod lib
  - if [ $POD_LIB_LINT == "YES" ]; then
      pod repo update;
      pod lib lint;
    fi

after_success:
  # Generate and publish docs
  - if [ -n "${TRAVIS_TAG}" ] && [ $PUBLISH_DOCS == "YES" ]; then
      ./CI/publish-docs.sh;
    fi

before_deploy:
  - carthage archive

deploy:
  # Upload framework to gh-releases for carthage
  - provider: releases
    api_key:
      secure: KoovDyi1gvzeDdGWKUPq2IEkpiC/6PadkIVEEkh+lyqBpWliC3KOu3cD/RXBAJw84g+YNUFr80776Xv/QPdj1LzTaN0Ri2HpfdyEPFOHvhQKzxJG/jm4BZBV+CNJfLJZndvrF/ImeZgkRTk/MR83urBJfl4/UnPj77CZg+lpG88HtV3oN8OqxBPEy34D4MTsg3twL/Z/XYlYl3BMzVzJzY9teHxwwcEgYwsk8i0GUggTRO/cyTDqg9X/g1rqEPWzlX4S/hGVBCB6qrRrXXK96DYUic39LdNbt+so+8hJHO0ETxTtt7v1B59qZ0OUlQfSBeUqBIrJCFm3U7hR4UJqHbsUl3dyQ/WrZv28/AaAFYCRDTqZSE7oTXR9IhY+jlhLrU3n7ukYoG1Yhr11MQN1z8DgzIhdyWWX2DK16kgsIFC99AxkRQzmJdQqXMmtrR79UN0/8eKE4WAm8Ihji6fTTCm4zx3sfi1bTJ8bdzbFhgpqqUpAuKc7yGbOhRsnYsL+TTpQiVCGju/nUNEHmwUy+MmYkHlR8l1OHz0mGbZQMecUXZ8h4Be7RONIOaDB05Gi4wkcaywDkoUdEb9LuFIme+Ws+PbNEKwkcPIiv9tGzh/ROk9t7qWj3FU3R1oLQImpwBbIlywyelWrNfWE5QG928UmYNyK1RrpRBL8ekqqXlw=
    file: $FRAMEWORK_NAME.framework.zip
    skip_cleanup: true
    on:
      repo: VirgilSecurity/virgil-sdk-x
      tags: true
      condition: $PUBLISH_CARTHAGE = "YES"

  # Upload docs to gh-pages
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: "${TRAVIS_BUILD_DIR}/docs"
    on:
      tags: true
      condition: $PUBLISH_DOCS = "YES"
