name: deploy

on:
  push:
    tags:
    - '*'

jobs:
  Deploy:
    name: Deploy
    runs-on: macOS-12
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.4.1.app/Contents/Developer
    steps:
      - uses: actions/checkout@v3

      - name: Generate Docs
        run: ./CI/publish-docs.sh

      - name: Publish Docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs

      - name: Publish Cocoapods
        run: ./CI/publish-cocoapods.sh
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}

      # NOT supported for now due to issues with Carthage
      # - name: Build Carthage Binary
      #   run: |
      #       ./CI/publish-carthage.sh;
      # - name: Upload Carthage Binary
      #   uses: AButler/upload-release-assets@v2.0
      #   with:
      #     files: 'VirgilSDK.xcframework.zip'
      #     repo-token: ${{ secrets.GITHUB_TOKEN }}
